insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  201,
  'BENTLEY CONTINENTAL GT',
  '139 990',
  'premium',
  'Выбор для тех, кто ценит абсолютную роскошь и тишину движения.',
  'Выбор для тех, кто ценит абсолютную роскошь и тишину движения.',
  array['Натуральная кожа','Дворцовый комфорт','Мягкая поддержка','Ручная прострочка','Аристократичный статус'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Бело синий","hex":"#1e4fa8","splitHex":["#f5f5f5","#1e4fa8"]},{"name":"Белый","hex":"#f5f5f5"}]'::jsonb,
  '{"Бело синий":["/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (12)-Photoroom.png","/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (13)-Photoroom.png","/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (14)-Photoroom.png","/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (15)-Photoroom.png"],"Белый":["/chairs/premium/bentley-continental-gt/white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (15)-Photoroom.png","/chairs/premium/bentley-continental-gt/white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (16)-Photoroom.png"]}'::jsonb,
  null,
  '/chairs/premium/premium%20main%20photos/bentley.png',
  '["/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (12)-Photoroom.png","/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (13)-Photoroom.png","/chairs/premium/bentley-continental-gt/white-blue/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (14)-Photoroom.png"]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;

insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  202,
  'FERRARI F12',
  '139 990',
  'premium',
  'Выбор для тех, кто хочет эмоции и драйв без фильтров.',
  'Выбор для тех, кто хочет эмоции и драйв без фильтров.',
  array['Натуральная кожа','Спортивная посадка','Жёсткая фиксация','Гоночная эргономика','Итальянский темперамент'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Черно желтый","hex":"#1a1a1a","splitHex":["#1a1a1a","#f7c600"]}]'::jsonb,
  '{"Черно желтый":["/chairs/premium/ferrari-f12/black-yellow/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (7)-Photoroom.png"]}'::jsonb,
  null,
  '/chairs/premium/premium%20main%20photos/ferrari%20f12.png',
  '["/chairs/premium/ferrari-f12/black-yellow/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (7)-Photoroom.png"]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;

insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  203,
  'MERCEDES W223',
  '139 990',
  'premium',
  'Выбор для тех, кто выбирает технологии и безупречный комфорт.',
  'Выбор для тех, кто выбирает технологии и безупречный комфорт.',
  array['Натуральная кожа','Интеллектуальный комфорт','Адаптивная поддержка','Плавная посадка','Представительский статус'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Черный","hex":"#1a1a1a"},{"name":"Тиффани","hex":"#81d8d0"}]'::jsonb,
  '{"Черный":["/chairs/premium/mercedes-w223/black/gemini-3-pro-image-preview_a_сделай_фото_этого_кр (4)-Photoroom.png","/chairs/premium/mercedes-w223/black/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (17)-Photoroom.png","/chairs/premium/mercedes-w223/black/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (18)-Photoroom.png"],"Тиффани":["/chairs/premium/mercedes-w223/tiffany/gemini-3-pro-image-preview_a_сделай_фото_этого_кр-Photoroom.png","/chairs/premium/mercedes-w223/tiffany/gemini-3-pro-image-preview_a_сделай_фото_этого_кр (1)-Photoroom.png","/chairs/premium/mercedes-w223/tiffany/gemini-3-pro-image-preview_a_сделай_фото_этого_кр (2)-Photoroom.png","/chairs/premium/mercedes-w223/tiffany/gemini-3-pro-image-preview_a_сделай_фото_этого_кр (3)-Photoroom.png"]}'::jsonb,
  null,
  '/chairs/premium/premium%20main%20photos/w223.png',
  '["/chairs/premium/mercedes-w223/black/gemini-3-pro-image-preview_a_сделай_фото_этого_кр (4)-Photoroom.png","/chairs/premium/mercedes-w223/black/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (17)-Photoroom.png"]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;

insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  204,
  'BMW XM',
  '139 990',
  'premium',
  'Выбор для тех, кто хочет мощь, контроль и современный люкс.',
  'Выбор для тех, кто хочет мощь, контроль и современный люкс.',
  array['Натуральная кожа','Массивная поддержка','Спортивный баланс','Уверенная посадка','Прогрессивный характер'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Черно красный","hex":"#1a1a1a","splitHex":["#1a1a1a","#ff2847"]}]'::jsonb,
  '{"Черно красный":["/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (19)-Photoroom.png","/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (20)-Photoroom.png","/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (21)-Photoroom.png","/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (22)-Photoroom.png"]}'::jsonb,
  null,
  '/chairs/premium/premium%20main%20photos/bmw%20xm.png',
  '["/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (19)-Photoroom.png","/chairs/premium/bmw-xm/black-red/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (20)-Photoroom.png"]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;

insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  205,
  'LAMBORGHINI AVENTADOR',
  '139 990',
  'premium',
  'Выбор для тех, кто не признаёт компромиссов и хочет максимум адреналина.',
  'Выбор для тех, кто не признаёт компромиссов и хочет максимум адреналина.',
  array['Натуральная кожа','Агрессивная эргономика','Максимальная фиксация','Жёсткая посадка','Суперкар-статус'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Черно белый","hex":"#1a1a1a","splitHex":["#1a1a1a","#f5f5f5"]}]'::jsonb,
  '{"Черно белый":["/chairs/premium/lamborghini-aventador/black-white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (8)-Photoroom.png","/chairs/premium/lamborghini-aventador/black-white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (9)-Photoroom.png","/chairs/premium/lamborghini-aventador/black-white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (10)-Photoroom.png"]}'::jsonb,
  null,
  '/chairs/premium/premium%20main%20photos/lamborghini.png',
  '["/chairs/premium/lamborghini-aventador/black-white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (8)-Photoroom.png","/chairs/premium/lamborghini-aventador/black-white/gemini-3-pro-image-preview_a_сгенерируй_фото_этог (9)-Photoroom.png"]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;
