insert into products (
  id,
  name,
  price,
  segment,
  description,
  full_description,
  features,
  specs,
  colors,
  color_gallery,
  badge,
  image,
  gallery,
  is_upgrade
) values (
  205,
  'LAMBORGHINI AVENTADOR',
  '139 990',
  'premium',
  'Выбор для тех, кто не признаёт компромиссов и хочет максимум адреналина.',
  'Выбор для тех, кто не признаёт компромиссов и хочет максимум адреналина.',
  array['Натуральная кожа','Агрессивная эргономика','Максимальная фиксация','Жёсткая посадка','Суперкар-статус'],
  '[{"label":"Макс. нагрузка","value":"150 кг"},{"label":"Высота спинки","value":"? см"},{"label":"Ширина сиденья","value":"? см"},{"label":"Угол наклона","value":"90° - 180°"},{"label":"Каркас","value":"Сталь?"},{"label":"Гарантия","value":"1 год"}]'::jsonb,
  '[{"name":"Черно белый","hex":"#1a1a1a","splitHex":["#1a1a1a","#f5f5f5"]}]'::jsonb,
  null,
  null,
  '',
  '[]'::jsonb,
  false
) on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  segment = excluded.segment,
  description = excluded.description,
  full_description = excluded.full_description,
  features = excluded.features,
  specs = excluded.specs,
  colors = excluded.colors,
  color_gallery = excluded.color_gallery,
  badge = excluded.badge,
  image = excluded.image,
  gallery = excluded.gallery,
  is_upgrade = excluded.is_upgrade;
